FROM python:3.8-slim

RUN apt-get update \ 
 && apt-get install -y supervisor nginx

COPY ./models/requirements.txt /app/models/requirements.txt
COPY ./api/requirements.txt /app/api/requirements.txt
RUN cd /app \
 && pip3 install -r api/requirements.txt -r models/requirements.txt

COPY ./models /app/models
COPY ./api /app/api
RUN cd /app && pip3 install ./api ./models

COPY ./supervisord.conf /etc/supervisor/supervisord.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./static /static

CMD sed -i 's/listen 80;/listen '"$PORT"';/' /etc/nginx/nginx.conf && /usr/bin/supervisord
