version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports: 
      - 8000:80
      - 8888:8888
    environment:
      PORT: 80
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./models:/app/models
      - ./api:/app/api
      - ./static:/static
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      TWITCH_CHANNELS: ${TWITCH_CHANNELS}
      TWITCH_IRC_TOKEN: ${TWITCH_IRC_TOKEN}
      API_URL: ${API_URL}
    volumes:
      - ./bot:/app/bot
