FROM nginx:stable

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./static /static

RUN apt-get update && apt-get install -y supervisor
COPY ./supervisord.conf /etc/supervisor/supervisord.conf

CMD sed -i 's/listen 80;/listen '"$PORT"';/' /etc/nginx/nginx.conf && /usr/bin/supervisord
