"""create tier clip columns for user

Revision ID: f0878fe50c47
Revises: 472352765f6a
Create Date: 2020-06-08 23:44:39.198135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0878fe50c47'
down_revision = '472352765f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clip_1_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('clip_2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'clip', ['clip_2_id'], ['id'])
    op.create_foreign_key(None, 'user', 'clip', ['clip_1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'clip_2_id')
    op.drop_column('user', 'clip_1_id')
    # ### end Alembic commands ###
