"""more columns for clips

Revision ID: 84efecce5b86
Revises: f0878fe50c47
Create Date: 2020-06-09 01:03:40.955225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84efecce5b86'
down_revision = 'f0878fe50c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('broadcaster_id', sa.Integer(), nullable=True))
    op.add_column('clip', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('clip', sa.Column('curator_id', sa.Integer(), nullable=True))
    op.add_column('clip', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('clip', sa.Column('game', sa.String(), nullable=True))
    op.add_column('clip', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('clip', sa.Column('title', sa.String(), nullable=True))
    op.add_column('clip', sa.Column('views', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clip', 'user', ['broadcaster_id'], ['id'])
    op.create_foreign_key(None, 'clip', 'user', ['curator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clip', type_='foreignkey')
    op.drop_constraint(None, 'clip', type_='foreignkey')
    op.drop_column('clip', 'views')
    op.drop_column('clip', 'title')
    op.drop_column('clip', 'thumbnail')
    op.drop_column('clip', 'game')
    op.drop_column('clip', 'duration')
    op.drop_column('clip', 'curator_id')
    op.drop_column('clip', 'created_at')
    op.drop_column('clip', 'broadcaster_id')
    # ### end Alembic commands ###
