"""name only for curator and broadcaster

Revision ID: 3cada449cedf
Revises: 84efecce5b86
Create Date: 2020-06-09 22:16:07.244162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cada449cedf'
down_revision = '84efecce5b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('broadcaster', sa.String(), nullable=True))
    op.add_column('clip', sa.Column('curator', sa.String(), nullable=True))
    op.drop_constraint('clip_curator_id_fkey', 'clip', type_='foreignkey')
    op.drop_constraint('clip_broadcaster_id_fkey', 'clip', type_='foreignkey')
    op.drop_column('clip', 'curator_id')
    op.drop_column('clip', 'broadcaster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('broadcaster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clip', sa.Column('curator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('clip_broadcaster_id_fkey', 'clip', 'user', ['broadcaster_id'], ['id'])
    op.create_foreign_key('clip_curator_id_fkey', 'clip', 'user', ['curator_id'], ['id'])
    op.drop_column('clip', 'curator')
    op.drop_column('clip', 'broadcaster')
    # ### end Alembic commands ###
